### ISSUE TITLE
npm上的antd组件在IE8下是有问题的，因为保留字default

### ISSUE THREAD

**Issue by codering** [fis-components/antd#2]
看下这个issue
[https://github.com/ant-tool/atool-build/issues/28](https://github.com/ant-tool/atool-build/issues/28)
fis3该怎么解决这个问题？

实在不行我只能用jsx自己编译了。。。。

**Comment by codering** [comment]
我用的fis3, 自己写个基于es3ify的parser插件解决了。

**Comment by 2betop** [comment]
不错，求插件地址。

**Comment by codering** [comment]
[https://www.npmjs.com/package/fis3-parser-translate-es3ify](https://www.npmjs.com/package/fis3-parser-translate-es3ify)

**Comment by codering** [comment]
写的很简单，fis3扩展超方便！  https://github.com/ant-design/ant-design/issues/858

**Comment by 2betop** [comment]
awesome!!!
